/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run yarn compile-schemas to regenerate this file.
 */

export interface Conflict {
  statusCode: 409;
  error: "Conflict";
  message?: string;
}
