# Api

## Genres

### List genres
GET http://localhost:3000/api/genres

### Create a new genre
POST http://localhost:3000/api/genres
Content-Type:  application/json

{
  "name": "Horror",
  "slug": "horror"
}
