version: 2.1

executors:
  node_lts: # declares a reusable executor
    docker:
      - image: &NODE_VERSION node:16.14.2

jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v16-{{ checksum "yarn.lock" }}
            - yarn-v16

      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-v16-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      # Run linting
      - run: yarn lint

      # Build
      - run: yarn build

      # Pass to other jobs
      - persist_to_workspace:
          root: ./
          paths: ./

  test:
    docker:
      - image: *NODE_VERSION
      - image: mongo:4.4.13
    executor: node_lts
    environment:
      MONGO_URI: mongodb://localhost/webshop-node-2021
    steps:
      - attach_workspace:
          at: ./
      - run: yarn migrate up
      - run: mkdir ~/jest
      - run: JEST_JUNIT_OUTPUT_DIR=~/jest JEST_JUNIT_OUTPUT_NAME=test--junit.xml yarn jest --runInBand --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ~/jest
      - store_artifacts:
          path: ~/jest

workflows:
  version: 2
  complete:
    jobs:
      - build
      - test:
          requires:
            - build
