version: 2.1

executors:
  node_lts: # declares a reusable executor
    docker:
      - image: &NODE_VERSION node:18.15.0

jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v18-{{ checksum "yarn.lock" }}
            - yarn-v18

      - run:
          name: install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-v18-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      # Run linting
      - run: yarn lint

      # Build
      - run: yarn build

      # Pass to other jobs
      - persist_to_workspace:
          root: ./
          paths: ./

  test:
    docker:
      - image: *NODE_VERSION
      - image: mongo:4.4.13
    executor: node_lts
    environment:
      MONGO_URI: mongodb://localhost/webshop-node-2021
    steps:
      - attach_workspace:
          at: ./
      - run: mkdir ~/junit
      - run: yarn migrate up
      - run:
          command: MOCHA_FILE=~/junit/test-results.xml npx mocha -- --reporter=mocha-junit-reporter
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

workflows:
  version: 2
  complete:
    jobs:
      - build
      - test:
          requires:
            - build
