/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run yarn compile-schemas to regenerate this file.
 */

export interface Env {
  LOG_LEVEL?: "fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent";
  MONGO_URI: string;
  PORT?: string;
  RUNTIME_ENV?: "local" | "test" | "dev" | "sta" | "pro";
}
