/* eslint-disable no-console */
/* eslint-disable import/no-extraneous-dependencies */
import { writeFile } from 'fs/promises';
import glob from 'glob';
import { compileFromFile } from 'json-schema-to-typescript';
import path from 'path';

glob('src/**/*.schema.json', {}, async (err, files) => {
  if (err) console.error(err);

  const bannerComment = `
/* tslint:disable */
/**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run yarn compile-schemas to regenerate this file.
*/
`;

  for await (const file of files) {
    const ts = await compileFromFile(file, {
      bannerComment,
    });

    const parsed = path.parse(file);

    await writeFile(
      `${parsed.dir}/${parsed.name.split('.')[0]}.type.d.ts`,
      ts,
    );
  }
});
